{{ if .Values.agent.registerjson -}}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ template "agent-group.name" . }}-registerjson'
  annotations:
    description: "{{ .Chart.Description }}"
  labels:
    app: '{{ template "agent-group.name" . }}'
    chart: '{{ template "agent-group.chart" . }}'
    component: agent-group
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  register.json: {{ toJson .Values.agent.registerjson | b64enc }}
{{- end }}
