name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: lint
        name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: lint
          config: ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-alpha.3
        with:
          installLocalPathProvisioner: true
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: install
          config: ct.yaml
