name: Release

on:
  push:
    branches:
      - master

jobs:
  lint-test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: lint
        name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: lint
          config: ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-alpha.3
        with:
          installLocalPathProvisioner: true
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: install
          config: ct.yaml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - lint-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}"@users.noreply.github.com

      - name: Install helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-alpha.2
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
