name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - lint-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}"@users.noreply.github.com

      - name: Install helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-alpha.2
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
